# Generated by Django 3.2.9 on 2023-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20230706_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
    ]
