# Generated by Django 3.2.9 on 2023-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20230710_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ManyToManyField(related_name='reserve', to='hotel.Room')),
                ('staying_time', models.ManyToManyField(related_name='reserve', to='hotel.calender')),
            ],
        ),
    ]
