# Generated by Django 3.2.9 on 2023-07-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reserve_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve_item',
            name='room',
        ),
        migrations.AddField(
            model_name='reserve_item',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='hotel.room'),
        ),
    ]
