# Generated by Django 3.2.9 on 2023-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20230710_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve_item',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
