# Generated by Django 4.2.3 on 2023-07-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_reserve_item_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(verbose_name='Requested Date')),
                ('results', models.CharField(max_length=200)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Installation_requests', to='hotel.room')),
            ],
        ),
    ]
