# Generated by Django 4.2.3 on 2023-07-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0009_installation_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation_request',
            name='room',
        ),
        migrations.AddField(
            model_name='installation_request',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='accounts.guest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installation_request',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='installation_request',
            name='results',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
