# Generated by Django 3.2.9 on 2023-07-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0010_auto_20230712_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Reserves', to='accounts.guest'),
        ),
    ]
