# Generated by Django 4.2.3 on 2023-07-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0010_remove_installation_request_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation_request',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='using', to='accounts.guest'),
        ),
    ]
