# Generated by Django 4.2.3 on 2023-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_order_email_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
