# Generated by Django 3.2.9 on 2023-07-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0011_alter_reserves_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('1', 'restaurant'), ('2', 'housekeeping'), ('3', 'installations'), ('4', 'reservation')], default=4, max_length=1)),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[('p', 'paid'), ('u', 'unpaid')], default='u', max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('bill_item', models.ManyToManyField(related_name='bill', to='hotel.bill_item')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='accounts.guest')),
            ],
        ),
    ]
