# Generated by Django 4.2.3 on 2023-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_installation_request_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation_request',
            name='roomNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
