# Generated by Django 3.2.9 on 2023-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_bill_bill_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_item',
            name='cancle',
            field=models.CharField(blank=True, choices=[('n', 'exists'), ('y', 'cancled')], default='n', max_length=1, null=True),
        ),
    ]
