# Generated by Django 4.2.3 on 2023-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_order_date_alter_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='')),
                ('email', models.CharField(default='')),
            ],
        ),
    ]
