# Generated by Django 4.2.3 on 2023-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_installation_request_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation_request',
            name='roomNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
