# Generated by Django 3.2.9 on 2023-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_bill_item_cancle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
