# Generated by Django 4.2.3 on 2023-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_installation_request_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation_request',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='installation_request',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installation_request',
            name='results',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
