# Generated by Django 4.2.3 on 2023-07-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0014_alter_installation_request_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeping_request',
            fields=[
                ('description', models.CharField(default='none', max_length=200)),
                ('request_date', models.DateTimeField(verbose_name='Requested Date')),
                ('results', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('roomNumber', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guest')),
            ],
        ),
    ]
