# Generated by Django 4.2.3 on 2023-07-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_rename_username_internetaccount_password'),
        ('hotel', '0015_housekeeping_request'),
    ]

    operations = [
    ]
