# Generated by Django 4.2.3 on 2023-07-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_merge_20230713_1240'),
        ('hotel', '0016_merge_20230713_1626'),
    ]

    operations = [
    ]
